# template-values.yaml: Helm values template for PascalIske code-server chart
# This file uses placeholder variables replaced by deploy-code-server.sh
# Placeholders: ${NAMESPACE}, ${STORAGE_SIZE}, ${CODE_SERVER_PASSWORD}, ${TIMEZONE}, ${SERVICE_TYPE}

# Image configuration for code-server
image:
  repository: codercom/code-server
  tag: latest

# Volume configuration - use existing PVC created by Terraform
volume:
  enabled: true
  existingClaim: code-server-pvc
  size: ${STORAGE_SIZE}  # Not used if existingClaim is set, but kept for reference

# Injector configuration (default for the chart)
injector:
  image:
    repository: ghcr.io/pascaliske/injector
    tag: latest

# Config environment variables for code-server
config:
  env:
    - name: PASSWORD
      value: "${CODE_SERVER_PASSWORD}"
    - name: TZ
      value: "${TIMEZONE}"
  yaml: ""

# Service configuration
service:
  type: ${SERVICE_TYPE}
  port: 80
  annotations: {}

# Ingress disabled since using LoadBalancer or ClusterIP
ingress:
  enabled: false

# Spot-specific environment variables
env:
  - name: SPOT_REGION
    value: "${SPOT_REGION}"
  - name: SPOT_GENERATION
    value: "${SPOT_GENERATION}"
  - name: SPOT_WEBHOOK_URL
    value: "${SPOT_WEBHOOK_URL}"

# GPU Support Configuration (enabled when GPU server classes are selected)
gpu:
  enabled: ${GPU_ENABLED:-false}  # Set to true when deploying to GPU-enabled node pools
  nodeSelector:
    nvidia.com/gpu: "present"  # Select nodes with NVIDIA GPUs
  tolerations:
    - key: "nvidia.com/gpu"
      operator: "Equal"
      value: "present"
      effect: "NoSchedule"
  # NVIDIA GPU Device Plugin DaemonSet (required for GPU workloads)
  devicePlugin:
    enabled: ${GPU_DEVICE_PLUGIN_ENABLED:-false}  # Enable NVIDIA device plugin when using GPU nodes
    image:
      repository: "nvcr.io/nvidia/k8s-device-plugin"
      tag: "v0.14.1"
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "50m"
        memory: "100Mi"
      limits:
        cpu: "100m"
        memory: "200Mi"
    args:
      - "--pass-device-specs"
      - "--fail-on-init-error"
      - "--device-list-strategy=envvar"
  # GPU Resource Requests/Limits for code-server pod
  resources:
    limits:
      nvidia.com/gpu: ${GPU_COUNT:-0}  # Request GPUs based on server class selection
    requests:
      nvidia.com/gpu: ${GPU_COUNT:-0}